# Generated by Django 3.2.4 on 2022-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称/标题')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('link', models.CharField(max_length=500, verbose_name='链接地址')),
                ('is_http', models.BooleanField(default=False, verbose_name='是否外链')),
                ('position', models.SmallIntegerField(choices=[(0, '头部'), (1, '脚部')], default=0, verbose_name='导航位置')),
            ],
            options={
                'verbose_name': '导航信息',
                'verbose_name_plural': '导航信息',
                'db_table': 'fg_nav',
            },
        ),
    ]
